WITH U AS (SELECT *
           FROM USERS
           WHERE BANNED = 'No')

SELECT REQUEST_AT DAY, ROUND(AVG(IF(STATUS = 'completed', 0, 1)), 2) AS 'CANCELLATION RATE'
FROM TRIPS
WHERE CLIENT_ID IN (SELECT USERS_ID FROM U)
  AND DRIVER_ID IN (SELECT USERS_ID FROM U)
  AND REQUEST_AT >= '2013-10-01'
  AND REQUEST_AT <= '2013-10-03'
GROUP BY REQUEST_AT
