WITH T1 AS (SELECT USERS_ID
            FROM USERS
            WHERE BANNED = 'Yes')

SELECT REQUEST_AT DAY, ROUND(SUM(IF(STATUS = 'completed', 0, 1)) / COUNT(*), 2) AS 'CANCELLATION RATE'
FROM TRIPS
WHERE CLIENT_ID NOT IN (SELECT * FROM T1)
  AND DRIVER_ID NOT IN (SELECT * FROM T1)
  AND REQUEST_AT >= '2013-10-01'
  AND REQUEST_AT <= '2013-10-03'
GROUP BY DAY
