SELECT A.CATEGORY, A.PRICE, PRODUCT_NAME FROM FOOD_PRODUCT A
INNER JOIN (
    SELECT CATEGORY, MAX(PRICE) PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) B ON A.CATEGORY = B.CATEGORY AND A.PRICE = B.PRICE AND A.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY A.PRICE DESC;