CREATE FUNCTION `getNthHighestSalary`(
    RNK INTEGER
) RETURNS INTEGER
BEGIN
RETURN (SELECT SALARY
        FROM (SELECT RANK() OVER (ORDER BY SALARY DESC) RNUM, SALARY
              FROM EMPLOYEE
              GROUP BY SALARY) A
        WHERE RNUM = RNK);
END