WITH T1 AS (SELECT BUYER_ID, COUNT(*) CNT
            FROM ORDERS
            WHERE YEAR (ORDER_DATE) = 2019
GROUP BY BUYER_ID
    )

SELECT A.USER_ID        BUYER_ID,
       A.JOIN_DATE,
       IFNULL(B.CNT, 0) ORDERS_IN_2019
FROM USERS A
         LEFT JOIN T1 B
                   ON A.USER_ID = B.BUYER_ID
