WITH T1 AS (SELECT BUYER_ID, COUNT(*) ORDERS_IN_2019
            FROM ORDERS
            WHERE YEAR (ORDER_DATE) = 2019
GROUP BY BUYER_ID
    )

SELECT A.USER_ID BUYER_ID, A.JOIN_DATE, IFNULL(B.ORDERS_IN_2019, 0) ORDERS_IN_2019
FROM USERS A
         LEFT OUTER JOIN T1 B
                         ON A.USER_ID = B.BUYER_ID