SELECT
    A.USER_ID BUYER_ID,
    JOIN_DATE,
    IFNULL(CNT, 0) ORDERS_IN_2019
FROM USERS A LEFT JOIN (
    SELECT BUYER_ID, COUNT(*) CNT
    FROM ORDERS
    WHERE YEAR(ORDER_DATE) = 2019
    GROUP BY BUYER_ID
) B
ON A.USER_ID = B.BUYER_ID