SELECT ACTIVITY_DATE DAY, COUNT(USER_ID) ACTIVE_USERS
FROM (SELECT ACTIVITY_DATE, USER_ID
      FROM ACTIVITY
      WHERE DATEDIFF('2019-07-27', ACTIVITY_DATE) BETWEEN 0 AND 29
      GROUP BY ACTIVITY_DATE, USER_ID) A
GROUP BY ACTIVITY_DATE