(SELECT A.NAME RESULTS
 FROM USERS A,
      MOVIERATING B
 WHERE A.USER_ID = B.USER_ID
 GROUP BY A.NAME
 ORDER BY COUNT(*) DESC, A.NAME LIMIT 1)
UNION ALL
(SELECT C.TITLE RESULTS
 FROM MOVIES C,
      MOVIERATING D
 WHERE C.MOVIE_ID = D.MOVIE_ID
   AND DATE_FORMAT(D.CREATED_AT, "%Y-%m") = '2020-02'
 GROUP BY C.TITLE
 ORDER BY AVG(D.RATING) DESC, C.TITLE LIMIT 1)
