(SELECT B.NAME RESULTS
 FROM MOVIERATING A,
      USERS B
 WHERE A.USER_ID = B.USER_ID
 GROUP BY B.USER_ID
 ORDER BY COUNT(A.RATING) DESC, B.NAME LIMIT 1)
UNION ALL
(SELECT B.TITLE RESULTS
 FROM MOVIERATING A,
      MOVIES B
 WHERE A.MOVIE_ID = B.MOVIE_ID
   AND DATE_FORMAT(A.CREATED_AT, '%Y-%m') = '2020-02'
 GROUP BY B.MOVIE_ID
 ORDER BY AVG(A.RATING) DESC, B.TITLE LIMIT 1)