WITH T1 AS (SELECT TIV_2015
            FROM INSURANCE
            GROUP BY TIV_2015
            HAVING COUNT(*) > 1),
     T2 AS (SELECT LAT, LON
            FROM INSURANCE
            GROUP BY LAT, LON
            HAVING COUNT(*) = 1)

SELECT ROUND(SUM(TIV_2016), 2) TIV_2016
FROM INSURANCE
WHERE TIV_2015 IN (SELECT * FROM T1)
  AND (LAT, LON) IN (SELECT * FROM T2)