WITH A AS (SELECT TIV_2015
           FROM INSURANCE
           GROUP BY TIV_2015
           HAVING COUNT(*) > 1),
     B AS (SELECT LAT, LON
           FROM INSURANCE
           GROUP BY LAT, LON
           HAVING COUNT(*) = 1)

SELECT ROUND(SUM(TIV_2016), 2) TIV_2016
FROM INSURANCE C
         JOIN A
         JOIN B
              ON C.TIV_2015 = A.TIV_2015 AND C.LAT = B.LAT AND C.LON = B.LON