WITH B AS (SELECT SALARY
           FROM (SELECT SALARY, DENSE_RANK() OVER(ORDER BY SALARY DESC) RNK
                 FROM EMPLOYEE) A
           WHERE RNK = 2)

(SELECT SALARY SecondHighestSalary FROM B)
UNION
(SELECT NULL SecondHighestSalary FROM EMPLOYEE LIMIT 1)
LIMIT 1