SELECT D.NAME Department, T.NAME Employee, T.SALARY Salary
FROM (SELECT NAME,
             SALARY,
             DEPARTMENTID,
             DENSE_RANK() OVER (PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) AS RANKNO
      FROM EMPLOYEE) T,
     DEPARTMENT D
WHERE T.DEPARTMENTID = D.ID
  AND T.RANKNO <= 3
ORDER BY D.ID, T.SALARY DESC;
