SELECT B.NAME DEPARTMENT, A.NAME EMPLOYEE, A.SALARY
FROM EMPLOYEE A
         JOIN DEPARTMENT B
              ON A.DEPARTMENTID = B.ID
WHERE (A.DEPARTMENTID, A.SALARY) IN (SELECT DEPARTMENTID, MAX(SALARY)
                                     FROM EMPLOYEE
                                     GROUP BY DEPARTMENTID)