SELECT B.NAME DEPARTMENT, A.NAME EMPLOYEE, A.SALARY
FROM EMPLOYEE A,
     DEPARTMENT B
WHERE A.DEPARTMENTID = B.ID
  AND (DEPARTMENTID, SALARY) IN (SELECT DEPARTMENTID, MAX(SALARY) MAXSALARY
                                 FROM EMPLOYEE
                                 GROUP BY DEPARTMENTID)