SELECT D.NAME DEPARTMENT, C.NAME EMPLOYEE, C.SALARY
FROM (SELECT A.DEPARTMENTID, B.NAME, A.SALARY
      FROM (SELECT DEPARTMENTID, MAX(SALARY) SALARY
            FROM EMPLOYEE
            GROUP BY DEPARTMENTID) A
               JOIN EMPLOYEE B
                    ON A.DEPARTMENTID = B.DEPARTMENTID AND A.SALARY = B.SALARY) C
         JOIN DEPARTMENT D
              ON C.DEPARTMENTID = D.ID
