WITH TBL AS (SELECT NAME, SALARY, DEPARTMENTID, DENSE_RANK() OVER (PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) RNK
             FROM EMPLOYEE)

SELECT B.NAME DEPARTMENT, A.NAME EMPLOYEE, SALARY
FROM TBL A
         JOIN DEPARTMENT B
              ON A.DEPARTMENTID = B.ID
WHERE RNK <= 3