WITH T1 AS (SELECT PLAYER_ID, MIN(EVENT_DATE) START
            FROM ACTIVITY
            GROUP BY PLAYER_ID)

SELECT ROUND(AVG(FLAG), 2) FRACTION
FROM (SELECT IF(SUM(DIFF) > 0, 1, 0) FLAG
      FROM (SELECT T1.PLAYER_ID, IF(DATEDIFF(ACTIVITY.EVENT_DATE, START) = 1, 1, 0) DIFF
            FROM ACTIVITY,
                 T1
            WHERE ACTIVITY.PLAYER_ID = T1.PLAYER_ID) A
      GROUP BY PLAYER_ID) B