SELECT ROUND(COUNT(*) / (SELECT COUNT(*) FROM (SELECT PLAYER_ID FROM ACTIVITY GROUP BY PLAYER_ID) C), 2) FRACTION
FROM (SELECT PLAYER_ID, MIN(EVENT_DATE) DATE
      FROM ACTIVITY
      GROUP BY PLAYER_ID) A
         JOIN ACTIVITY B
WHERE DATEDIFF(B.EVENT_DATE, A.DATE) = 1
  AND A.PLAYER_ID = B.PLAYER_ID