SELECT B.ID, C.AGE, A.MIN_COINS, A.POWER
FROM (SELECT CODE, POWER, MIN(COINS_NEEDED) AS MIN_COINS
      FROM WANDS
      GROUP BY CODE, POWER) A
         LEFT JOIN WANDS B
                   ON A.CODE = B.CODE AND A.MIN_COINS = B.COINS_NEEDED
         LEFT JOIN WANDS_PROPERTY C
                   ON A.CODE = C.CODE
WHERE C.IS_EVIL = 0
ORDER BY A.POWER DESC, C.AGE DESC