SELECT YEAR, MONTH, GENDER, COUNT(USER_ID) USERS FROM (
    SELECT YEAR(A.SALES_DATE) YEAR, MONTH(A.SALES_DATE) MONTH, B.GENDER GENDER, A.USER_ID FROM ONLINE_SALE A, USER_INFO B
    WHERE A.USER_ID = B.USER_ID AND B.GENDER IS NOT NULL
    GROUP BY YEAR, MONTH, GENDER, A.USER_ID) C
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;