SELECT MONTH(START_DATE) MONTH, A.CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A, (
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) >= 8 AND MONTH(START_DATE) <= 10
    GROUP BY CAR_ID HAVING COUNT(*) >= 5) B
WHERE A.CAR_ID = B.CAR_ID AND MONTH(START_DATE) >= 8 AND MONTH(START_DATE) <= 10
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC;