SELECT F.HACKER_ID, F.NAME
FROM HACKERS F
         JOIN
     (SELECT HACKER_ID, COUNT(*) CNT
      FROM (SELECT HACKER_ID, C.CHALLENGE_ID
            FROM SUBMISSIONS C
                     JOIN
                 (SELECT A.DIFFICULTY_LEVEL, A.SCORE, B.CHALLENGE_ID
                  FROM DIFFICULTY A
                           JOIN CHALLENGES B
                                ON A.DIFFICULTY_LEVEL = B.DIFFICULTY_LEVEL) D
                 ON C.CHALLENGE_ID = D.CHALLENGE_ID AND C.SCORE = D.SCORE) E
      GROUP BY HACKER_ID
      HAVING COUNT(*) > 1) G ON F.HACKER_ID = G.HACKER_ID
ORDER BY CNT DESC, F.HACKER_ID