SELECT A.PRODUCT_CODE, A.PRICE * B.CNT SALES
FROM PRODUCT A,
     (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) CNT
      FROM OFFLINE_SALE
      GROUP BY PRODUCT_ID) B
WHERE A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY SALES DESC, A.PRODUCT_CODE