SELECT A.*, B.CNT, C.CNT, D.CNT, E.CNT
FROM COMPANY A,
     (SELECT COMPANY_CODE, COUNT(*) CNT
      FROM (SELECT LEAD_MANAGER_CODE, COMPANY_CODE FROM LEAD_MANAGER GROUP BY LEAD_MANAGER_CODE, COMPANY_CODE) T1
      GROUP BY COMPANY_CODE) B,
     (SELECT COMPANY_CODE, COUNT(*) CNT
      FROM (SELECT SENIOR_MANAGER_CODE, COMPANY_CODE FROM SENIOR_MANAGER GROUP BY SENIOR_MANAGER_CODE, COMPANY_CODE) T2
      GROUP BY COMPANY_CODE) C,
     (SELECT COMPANY_CODE, COUNT(*) CNT
      FROM (SELECT MANAGER_CODE, COMPANY_CODE FROM MANAGER GROUP BY MANAGER_CODE, COMPANY_CODE) T3
      GROUP BY COMPANY_CODE) D,
     (SELECT COMPANY_CODE, COUNT(*) CNT
      FROM (SELECT EMPLOYEE_CODE, COMPANY_CODE FROM EMPLOYEE GROUP BY EMPLOYEE_CODE, COMPANY_CODE) T4
      GROUP BY COMPANY_CODE) E
WHERE A.COMPANY_CODE = B.COMPANY_CODE
  AND B.COMPANY_CODE = C.COMPANY_CODE
  AND C.COMPANY_CODE = D.COMPANY_CODE
  AND D.COMPANY_CODE = E.COMPANY_CODE
ORDER BY A.COMPANY_CODE
