SELECT DISTINCT N2 ConsecutiveNums
FROM (SELECT LEAD(NUM, 1) OVER(ORDER BY ID) N1, NUM N2,
             LAG(NUM, 1)  OVER(ORDER BY ID) N3, LEAD(ID, 1) OVER(ORDER BY ID) I1, ID I2,
             LAG(ID, 1)   OVER(ORDER BY ID) I3
      FROM LOGS) A
WHERE N1 = N2
  AND N2 = N3
  AND I1 = I2 + 1
  AND I2 = I3 + 1