WITH T1 AS (SELECT HACKER_ID, COUNT(*) CNT
            FROM CHALLENGES
            GROUP BY HACKER_ID),
     T2 AS (SELECT CNT
            FROM T1
            WHERE CNT != (SELECT MAX (CNT) FROM T1)
GROUP BY CNT
HAVING COUNT (*) = 1
    )

SELECT A.HACKER_ID, B.NAME, A.CNT CHALLENGES_CREATED
FROM (SELECT HACKER_ID, CNT
      FROM T1
      WHERE CNT = (SELECT MAX(CNT) FROM T1) || CNT IN (SELECT * FROM T2)) A
         JOIN HACKERS B ON A.HACKER_ID = B.HACKER_ID
ORDER BY A.CNT DESC, A.HACKER_ID