SELECT C.PRODUCT_ID, IFNULL(NEW_PRICE, 10) PRICE
FROM (SELECT PRODUCT_ID, NEW_PRICE
      FROM (SELECT PRODUCT_ID,
                   CHANGE_DATE,
                   NEW_PRICE,
                   RANK() OVER (PARTITION BY PRODUCT_ID ORDER BY CHANGE_DATE DESC) RNK
            FROM PRODUCTS
            WHERE CHANGE_DATE <= '2019-08-16') A
      WHERE RNK = 1) B
         RIGHT JOIN (SELECT DISTINCT PRODUCT_ID FROM PRODUCTS) C
                    ON B.PRODUCT_ID = C.PRODUCT_ID