WITH T1 AS (
    SELECT PRODUCT_ID, MAX(CHANGE_DATE) CHANGE_DATE
    FROM PRODUCTS
    WHERE CHANGE_DATE <= '2019-08-16'
    GROUP BY PRODUCT_ID
), T2 AS (
    SELECT PRODUCT_ID
    FROM PRODUCTS
    GROUP BY PRODUCT_ID HAVING MIN(CHANGE_DATE) > '2019-08-16'
)

(
    SELECT PRODUCT_ID, NEW_PRICE PRICE
    FROM PRODUCTS
    WHERE (PRODUCT_ID, CHANGE_DATE) IN (SELECT * FROM T1)
)
UNION
(
    SELECT PRODUCT_ID, 10 PRICE
    FROM PRODUCTS
    WHERE PRODUCT_ID IN (SELECT * FROM T2)
)
