SELECT MAX(IF(OCCUPATION = 'Doctor', NAME, NULL))    AS Doctor,
       MAX(IF(OCCUPATION = 'Professor', NAME, NULL)) AS Professor,
       MAX(IF(OCCUPATION = 'Singer', NAME, NULL))    AS Singer,
       MAX(IF(OCCUPATION = 'Actor', NAME, NULL))     AS Actor
FROM (SELECT ROW_NUMBER() OVER (PARTITION BY OCCUPATION ORDER BY NAME) AS RNUM, OCCUPATION,
             NAME
      FROM OCCUPATIONS) AS TMP
GROUP BY RNUM
ORDER BY RNUM
