SELECT A.PRODUCT_ID, IFNULL(ROUND(SUM(A.PRICE * B.UNITS) / SUM(B.UNITS), 2), 0) AVERAGE_PRICE
FROM PRICES A
         LEFT JOIN UNITSSOLD B
                   ON A.PRODUCT_ID = B.PRODUCT_ID AND B.PURCHASE_DATE BETWEEN A.START_DATE AND A.END_DATE
GROUP BY A.PRODUCT_ID