SELECT MIN(START_DATE), MAX(END_DATE)
FROM (SELECT START_DATE,
             END_DATE,
             START_DATE - ROW_NUMBER() OVER (ORDER BY START_DATE) RNK
      FROM PROJECTS) A
GROUP BY RNK
ORDER BY COUNT(*), MIN(START_DATE)
