SELECT USER_ID, NICKNAME, TOTAL_SALES FROM (
    SELECT WRITER_ID, SUM(PRICE) TOTAL_SALES FROM USED_GOODS_BOARD WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID HAVING SUM(PRICE) >= 700000) A,
    USED_GOODS_USER B
WHERE A.WRITER_ID = B.USER_ID
ORDER BY TOTAL_SALES;