SELECT CONTESTS.CONTEST_ID,
       CONTESTS.HACKER_ID,
       CONTESTS.NAME,
       SUM(TOTAL_SUBMISSIONS)          TOTAL_SUBMISSIONS,
       SUM(total_accepted_submissions) total_accepted_submissions,
       SUM(Total_views)                Total_views,
       SUM(total_unique_views)         total_unique_views
FROM CONTESTS
         JOIN COLLEGES ON CONTESTS.CONTEST_ID = COLLEGES.CONTEST_ID
         JOIN CHALLENGES ON COLLEGES.COLLEGE_ID = CHALLENGES.COLLEGE_ID
         LEFT JOIN
     (SELECT CHALLENGE_ID,
             SUM(TOTAL_VIEWS)        TOTAL_VIEWS,
             SUM(TOTAL_UNIQUE_VIEWS) TOTAL_UNIQUE_VIEWS
      FROM VIEW_STATS
      GROUP BY CHALLENGE_ID) A ON CHALLENGES.CHALLENGE_ID = A.CHALLENGE_ID
         LEFT JOIN
     (SELECT CHALLENGE_ID,
             SUM(TOTAL_SUBMISSIONS)          TOTAL_SUBMISSIONS,
             SUM(TOTAL_ACCEPTED_SUBMISSIONS) TOTAL_ACCEPTED_SUBMISSIONS
      FROM SUBMISSION_STATS
      GROUP BY CHALLENGE_ID) B ON CHALLENGES.CHALLENGE_ID = B.CHALLENGE_ID
GROUP BY CONTESTS.CONTEST_ID, CONTESTS.HACKER_ID, CONTESTS.NAME
HAVING SUM(TOTAL_SUBMISSIONS) != 0 OR
    SUM(total_accepted_submissions) != 0 OR
    SUM(TOTAL_VIEWS) != 0 OR
    SUM(total_unique_views) != 0
ORDER BY CONTESTS.CONTEST_ID;