SELECT A ID, COUNT(*) NUM
FROM (SELECT REQUESTER_ID A, ACCEPTER_ID B
      FROM REQUESTACCEPTED
      UNION
      SELECT ACCEPTER_ID A, REQUESTER_ID B
      FROM REQUESTACCEPTED) C
GROUP BY A
ORDER BY NUM DESC LIMIT 1