SELECT B.YEAR, (B.MAX - A.SIZE_OF_COLONY) YEAR_DEV, A.ID
FROM ECOLI_DATA A
         JOIN (SELECT MAX(SIZE_OF_COLONY) MAX, YEAR(DIFFERENTIATION_DATE) YEAR
               FROM ECOLI_DATA
               GROUP BY YEAR (DIFFERENTIATION_DATE)) B
              ON YEAR (A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY B.YEAR, YEAR_DEV
