WITH T1 AS (
    SELECT HACKER_ID, SUBMISSION_DATE, COUNT(*) CNT
    FROM (
             SELECT
                 HACKER_ID,
                 SUBMISSION_DATE,
                 DENSE_RANK() OVER (PARTITION BY HACKER_ID ORDER BY SUBMISSION_DATE) - DAY(SUBMISSION_DATE) DIFF
            FROM SUBMISSIONS
    ) A
    WHERE DIFF = 0
    GROUP BY HACKER_ID, SUBMISSION_DATE
), T2 AS (
    SELECT SUBMISSION_DATE, HACKER_ID
    FROM
        (
        SELECT
        SUBMISSION_DATE,
        HACKER_ID,
        RANK() OVER (PARTITION BY SUBMISSION_DATE ORDER BY COUNT(*) DESC, HACKER_ID) RNK
        FROM SUBMISSIONS
        GROUP BY SUBMISSION_DATE, HACKER_ID
        ) B
    WHERE RNK = 1
), T3 AS (
    SELECT SUBMISSION_DATE, COUNT(*) CNT
    FROM (
        SELECT SUBMISSION_DATE, HACKER_ID
        FROM T1
        GROUP BY SUBMISSION_DATE, HACKER_ID
        ) C
    GROUP BY SUBMISSION_DATE
)

SELECT T2.SUBMISSION_DATE, T3.CNT, T4.HACKER_ID, T4.NAME
FROM
    T2 JOIN T3 ON T2.SUBMISSION_DATE = T3.SUBMISSION_DATE
       JOIN HACKERS T4 ON T2.HACKER_ID = T4.HACKER_ID
ORDER BY T2.SUBMISSION_DATE
