SELECT ROUND(AVG(ORDER_DATE = CUSTOMER_PREF_DELIVERY_DATE) * 100, 2) immediate_percentage
FROM (SELECT CUSTOMER_ID,
             ORDER_DATE,
             CUSTOMER_PREF_DELIVERY_DATE,
             ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE) RNUM
      FROM DELIVERY) A
WHERE RNUM = 1