SELECT ROUND(AVG(IF(ORDER_DATE = CUSTOMER_PREF_DELIVERY_DATE, 1, 0)) * 100, 2) immediate_percentage
FROM (SELECT *, RANK() OVER (PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE, CUSTOMER_PREF_DELIVERY_DATE) RNK
      FROM DELIVERY
      ORDER BY CUSTOMER_ID, ORDER_DATE) A
WHERE RNK = 1