SELECT B.REPORTS_TO EMPLOYEE_ID, A.NAME, COUNT(*) REPORTS_COUNT, ROUND(AVG(B.AGE)) AVERAGE_AGE
FROM EMPLOYEES A
         JOIN EMPLOYEES B
              ON A.EMPLOYEE_ID = B.REPORTS_TO
GROUP BY B.REPORTS_TO
ORDER BY B.REPORTS_TO