WITH T1 AS (SELECT STUDENT_ID, SUBJECT_NAME, COUNT(*) CNT
            FROM EXAMINATIONS
            GROUP BY STUDENT_ID, SUBJECT_NAME),
     T2 AS (SELECT A.*, B.SUBJECT_NAME, B.CNT
            FROM STUDENTS A
                     JOIN T1 B
                          ON A.STUDENT_ID = B.STUDENT_ID),
     T3 AS (SELECT *
            FROM STUDENTS,
                 SUBJECTS)

SELECT T3.STUDENT_ID, T3.STUDENT_NAME, T3.SUBJECT_NAME, IFNULL(T2.CNT, 0) ATTENDED_EXAMS
FROM T2
         RIGHT OUTER JOIN T3
                          ON T2.SUBJECT_NAME = T3.SUBJECT_NAME AND T2.STUDENT_ID = T3.STUDENT_ID
ORDER BY T3.STUDENT_ID, T3.SUBJECT_NAME
