SELECT CUSTOMER_ID
FROM (SELECT CUSTOMER_ID, COUNT(*) CNT
      FROM (SELECT CUSTOMER_ID
            FROM CUSTOMER
            GROUP BY CUSTOMER_ID, PRODUCT_KEY) A
      GROUP BY CUSTOMER_ID) B
WHERE CNT = (SELECT COUNT(*)
             FROM PRODUCT);