SELECT CUSTOMER_ID
FROM (SELECT CUSTOMER_ID, PRODUCT_KEY
      FROM CUSTOMER
      GROUP BY CUSTOMER_ID, PRODUCT_KEY) A
GROUP BY CUSTOMER_ID
HAVING COUNT(*) = (SELECT COUNT(*)
                   FROM PRODUCT)
