SELECT * FROM (
    SELECT A.CAR_ID, A.CAR_TYPE, ROUND(A.F*((100-B.DISCOUNT_RATE)/100)*30) FEE FROM
        (SELECT CAR_ID, CAR_TYPE, DAILY_FEE F
         FROM CAR_RENTAL_COMPANY_CAR
         WHERE CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30')
           AND CAR_TYPE IN ('세단', 'SUV')) A,
        (SELECT CAR_TYPE, DISCOUNT_RATE
         FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
         WHERE DURATION_TYPE = '30일 이상') B
    WHERE A.CAR_TYPE = B.CAR_TYPE) C
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC