SELECT A.CART_ID FROM
                     (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Yogurt') A,
                     (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Milk') B
WHERE A.CART_ID = B.CART_ID GROUP BY CART_ID