SELECT A.HACKER_ID, A.NAME, B.TOTAL_SCORE
FROM HACKERS A
         JOIN (SELECT HACKER_ID, SUM(SCORE) TOTAL_SCORE
               FROM (SELECT HACKER_ID, MAX(SCORE) SCORE
                     FROM SUBMISSIONS
                     GROUP BY HACKER_ID, CHALLENGE_ID) C
               GROUP BY HACKER_ID
               HAVING SUM(SCORE) > 0) B
              ON A.HACKER_ID = B.HACKER_ID
ORDER BY TOTAL_SCORE DESC, A.HACKER_ID
