SELECT A.DEPT_ID, B.DEPT_NAME_EN, ROUND(A.AVG_SAL) AVG_SAL
FROM (SELECT DEPT_ID, AVG(SAL) AVG_SAL
      FROM HR_EMPLOYEES
      GROUP BY DEPT_ID) A
         JOIN HR_DEPARTMENT B
              ON A.DEPT_ID = B.DEPT_ID
ORDER BY AVG_SAL DESC
