SELECT A.SCORE, A.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL
FROM (SELECT EMP_NO, SUM(SCORE) SCORE
      FROM HR_GRADE
      GROUP BY EMP_NO) A
         JOIN HR_EMPLOYEES B
              ON A.EMP_NO = B.EMP_NO
ORDER BY A.SCORE DESC LIMIT 1
