SELECT DATE_FORMAT(TRANS_DATE, '%Y-%m') month,
       COUNTRY,
       COUNT(*)                               TRANS_COUNT,
       SUM(IF(STATE = 'APPROVED', 1, 0))      APPROVED_COUNT,
       SUM(AMOUNT)                            TRANS_TOTAL_AMOUNT,
       SUM(IF(STATE = 'APPROVED', AMOUNT, 0)) APPROVED_TOTAL_AMOUNT
FROM TRANSACTIONS
GROUP BY MONTH, COUNTRY