SELECT A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
FROM (SELECT ID, EMAIL, FIRST_NAME, LAST_NAME, CONV(SKILL_CODE, 10, 2) CODE
      FROM DEVELOPERS) A
         JOIN (SELECT CONV(CODE, 10, 2) CODE
               FROM SKILLCODES
               WHERE NAME = 'Python'
                  OR NAME = 'C#') B
              ON ROUND(A.CODE / B.CODE) LIKE '%1'
GROUP BY A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
ORDER BY A.ID
