SELECT CATEGORY, SUM(SALES) TOTAL_SALES
FROM (SELECT A.CATEGORY, B.SALES
      FROM BOOK A,
           BOOK_SALES B
      WHERE A.BOOK_ID = B.BOOK_ID
        AND DATE_FORMAT(B.SALES_DATE, "%Y-%m") = '2022-01') C
GROUP BY CATEGORY
ORDER BY CATEGORY;