SELECT STR
FROM (SELECT CONCAT(NAME, '(', SUBSTRING(OCCUPATION, 1, 1), ')') STR
      FROM OCCUPATIONS
      UNION
      SELECT CONCAT('There are a total of ', COUNT(*), ' ', LOWER(OCCUPATION), 's.') STR
      FROM OCCUPATIONS
      GROUP BY OCCUPATION) A
ORDER BY STR