-- 코드를 입력하세요
SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') CREATED_DATE
FROM USED_GOODS_BOARD A, USED_GOODS_REPLY B
WHERE A.BOARD_ID = B.BOARD_ID
AND A.CREATED_DATE >= '2022-10-01' AND A.CREATED_DATE <= '2022-10-30'
ORDER BY B.CREATED_DATE, A.TITLE;

/*
WHERE CREATED_DATE >= '2022-10-01'AND CREATED_DATE < '2022-11-01';
게시글 제목 : TITLE - USED_GOODS_BOARD
게시글 ID : BOARD_ID - USED_GOODS_BOARD, USED_GOODS_REPLY
댓글 ID : REPLY_ID - USED_GOODS_REPLY
댓글 작성자 ID : WRITER_ID - USED_GOODS_REPLY
*/
