SELECT D.ITEM_ID, D.ITEM_NAME, D.RARITY
FROM (SELECT A.ITEM_ID
      FROM ITEM_TREE A
               LEFT JOIN ITEM_TREE B
                         ON A.ITEM_ID = B.PARENT_ITEM_ID
      WHERE B.PARENT_ITEM_ID IS NULL) C
         JOIN ITEM_INFO D
              ON C.ITEM_ID = D.ITEM_ID
ORDER BY D.ITEM_ID DESC
